# ya pack -a jamylak/rose-pine
# [flavor]
# use = "rose-pine"
# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/theme.toml
[icon]
prepend_dirs  = [
	{ name = ".config", text = "î—¼ " , fg_dark = "#eca517", fg_light = "#76520c"},
	{ name = ".git", text = "ïˆ " , fg_dark = "#eca517", fg_light = "#76520c" },
	{ name = ".github", text = "ï‚’ ", fg_dark = "#eca517", fg_light = "#76520c"  },
	{ name = "gh", text = "ï‚’ ", fg_dark = "#eca517", fg_light = "#76520c" },
	{ name = "bar", text = "ğŸš§" },
	{ name = "proj", text = "ğŸ› ï¸" },
	{ name = "ghostty", text = "ğŸ‘»" },
	{ name = "fish", text = "ğŸ " },
	{ name = "apple", text = "ğŸ’»" },
	{ name = "applescripts", text = "ğŸ’»" },
	{ name = "kitty", text = "ğŸ˜º" },
	{ name = "helix", text = "ğŸ§¬" },
	{ name = ".helix", text = "ğŸ§¬" },
	{ name = "nvim", text = "î˜« ", fg_dark = "#eca517", fg_light = "#76520c"  },
	{ name = "nvim2", text = "î˜« ", fg_dark = "#eca517", fg_light = "#76520c"  },
	{ name = ".nvim", text = "î˜« ", fg_dark = "#eca517", fg_light = "#76520c"  },
	{ name = "vim", text = "î˜« ", fg_dark = "#eca517", fg_light = "#76520c"  },
	{ name = ".vim", text = "î˜« ", fg_dark = "#eca517", fg_light = "#76520c"  },
	{ name = ".vimrc", text = "î˜« ", fg_dark = "#eca517", fg_light = "#76520c"  },
	{ name = ".emacs.d", text = "î˜² ", fg_dark = "#eca517", fg_light = "#76520c"  },
	{ name = ".emacs.d.backup", text = "î˜² ", fg_dark = "#eca517", fg_light = "#76520c"  },
	{ name = ".viminfo", text = "î˜« " },
	{ name = ".viminfo.old", text = "î˜« " },
	{ name = ".tmux", text = "î¯ˆ " },
	{ name = ".cargo", text = "îš‹ ", fg_dark = "#eca517", fg_light = "#76520c" },
	{ name = "gcloud", text = "ó±‡¶ ", fg_dark = "#eca517", fg_light = "#76520c" },
	{ name = "docker", text = "ïŒˆ " },
	{ name = ".docker", text = "ïŒˆ ", fg_dark = "#eca517", fg_light = "#76520c" },
	{ name = ".cmake", text = "î™† ", fg_dark = "#eca517", fg_light = "#76520c" },
	{ name = "CMakeFiles", text = "î™† ", fg_dark = "#eca517", fg_light = "#76520c" },
	{ name = "tests", text = "ğŸ§ª" },
	{ name = "src", text = "ğŸ”¬" },
	{ name = "scripts", text = "ğŸ“œ" },
	# { name = "api", text = "ğŸ›œ" },
	# { name = "schemas", text = "â¨ " },
	# { name = "models", text = "ğŸŒ" },
	{ name = "web", text = "ğŸ•¸ï¸" },
	{ name = "docs", text = "ğŸ“–" },
	{ name = "doc", text = "ğŸ“–" },
	{ name = ".cache", text = "ó°ƒ¨ ", fg_dark = "#eca517", fg_light = "#76520c" },
	{ name = "build", text = "ğŸš§", fg_dark = "#eca517", fg_light = "#76520c" },
	{ name = "yazi", text = "ğŸ§°" },
	{ name = "Desktop", text = "ğŸ–¥ " },
	{ name = "Development", text = "ğŸ‘¨â€ğŸ’»" },
	{ name = "Documents", text = "ğŸ“œ" },
	{ name = "Downloads", text = "â˜ï¸" },
	{ name = "Library", text = "ğŸ“š" },
	{ name = "Movies", text = "ğŸ¥" },
	{ name = "Music", text = "ğŸµ" },
	{ name = "Pictures", text = "ğŸ“¸" },
	{ name = "Public", text = "ğŸ“¢" },
	{ name = "Videos", text = "ğŸ“¹" },
	{ name = "home", text = "ğŸ " },
	{ name = "private", text = "ğŸ”" },
	{ name = "tmp", text = "â³" },
	{ name = "Applications", text = "ğŸš€" },
	{ name = "Volumes", text = "ğŸ“€" },
	{ name = ".Trash", text = "ğŸ—‘ï¸" },
]
prepend_globs = [
		{ name = "**/*.app/", text = "ó°˜³ ", fg_dark = "#eca517", fg_light = "#76520c" },
]
prepend_files = [
		{ name = ".clang-format", text = "î™†", fg_dark = "#eca517", fg_light = "#76520c" },
		{ name = ".gitignore", text = "ó°Š¢", fg_dark = "#b9b9b9", fg_light = "#f1f1f1" },
		{ name = ".DS_Store", text = "î˜µ", fg_dark = "#b9b9b9", fg_light = "#f1f1f1" },
		{ name = "LICENSE", text = "ïƒ£", fg_dark = "#b9b9b9", fg_light = "#f1f1f1" },
		# { name = "Makefile", text = "ğŸšœ", fg_dark = "#b9b9b9", fg_light = "#f1f1f1" },
		{ name = "Makefile", text = "î™³", fg_dark = "#b9b9b9", fg_light = "#f1f1f1" },
		{ name = "go.mod", text = "î˜§", fg_dark = "#b9b9b9", fg_light = "#f1f1f1" },
		{ name = ".tmux.conf", text = "î¯ˆ" },
]
prepend_exts = [
		{ name = "txt", text = "ğŸ“" },
		{ name = "log", text = "ğŸªµ" },
		{ name = "vert", text = "ğŸ‘¾" },
		{ name = "frag", text = "ğŸ‘¾" },
		{ name = "spv", text = "ğŸ‘¾" },
		{ name = "geom", text = "ğŸ‘¾" },
		{ name = "tesc", text = "ğŸ‘¾" },
		{ name = "tese", text = "ğŸ‘¾" },
		{ name = "glsl", text = "ğŸ‘¾" },
		{ name = "hlsl", text = "ó°²", fg_dark = "#b9b9b9", fg_light = "#f1f1f1" },
		{ name = "metal", text = "î˜µ", fg_dark = "#b9b9b9", fg_light = "#f1f1f1" },
		{ name = "tfvars", text = "ó±¢" },
		{ name = "hcl", text = "ó±¢" },
]
prepend_conds = [
	# Special files
	# { if = "orphan", text = "ï±" },
	# { if = "link"  , text = "ï’" },
	# { if = "block" , text = "ïƒ‰" },
	# { if = "char"  , text = "ï‡€" },
	# { if = "fifo"  , text = "ï‡‘" },
	# { if = "sock"  , text = "ï‡¤" },
	# { if = "sticky", text = "ï‡¼" },
	# { if = "dummy",  text = "ï—" },

	# Fallback
	{ if = "hidden & dir", text = "ğŸ‘»" },
	{ if = "dir", text = "ğŸ—‚ï¸" },
	# { if = "exec", text = "î•" },
	# { if = "!dir", text = "ó°ˆ”" },
]

